<!DOCTYPE html>
<html lang="{{ $isUrdu ? 'ur' : 'en' }}" dir="{{ $isUrdu ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="UTF-8">
    <title>@lang('messages.audit_control_report')</title>
    <style>
        :root { --ink:#17212b; --muted:#687580; --line:#dce3e8; --blue:#1769aa; --green:#16794c; --red:#b42318; --amber:#9a6700; } *{box-sizing:border-box} body{margin:0;padding:32px;color:var(--ink);font:14px/1.5 "Segoe UI",Tahoma,sans-serif;background:#f4f6f8}.sheet{max-width:1150px;margin:auto;padding:42px 48px;background:#fff;box-shadow:0 5px 25px rgba(23,33,43,.08)}.header{display:flex;justify-content:space-between;border-bottom:3px solid var(--ink);padding-bottom:20px;margin-bottom:24px}h1,h2,h3,p{margin-top:0}h1{margin-bottom:4px;font-size:28px}h2{margin-bottom:4px;font-size:20px}.muted{color:var(--muted)}.period{text-align:{{ $isUrdu ? 'left' : 'right' }};color:var(--muted)}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:28px}.summary-card{padding:15px;border:1px solid var(--line);border-top:3px solid var(--blue)}.summary-card.danger{border-top-color:var(--red)}.summary-label{color:var(--muted);font-size:12px}.summary-value{margin-top:5px;font-size:22px;font-weight:700}.section{margin:28px 0}.section h3{padding-bottom:9px;border-bottom:2px solid var(--blue)}table{width:100%;border-collapse:collapse}th,td{padding:9px 12px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);background:#f7f9fa;font-size:12px;text-transform:uppercase;letter-spacing:.03em}.number{text-align:right;font-variant-numeric:tabular-nums}[dir="rtl"] .number{text-align:left}.badge{display:inline-block;padding:3px 8px;border-radius:12px;background:#e8f1f8;color:var(--blue);font-size:12px}.badge.danger{background:#fbe9e7;color:var(--red)}pre{margin:0;white-space:pre-wrap;word-break:break-word;font:11px/1.35 Consolas,monospace;color:#48545e}.empty{padding:20px;text-align:center;color:var(--muted)}.print{display:inline-block;margin-bottom:18px;padding:8px 14px;color:#fff;background:var(--blue);border:0;cursor:pointer}.footer{margin-top:36px;color:var(--muted);font-size:11px;text-align:center}@media print{body{padding:0;background:#fff}.sheet{padding:20px;box-shadow:none}.print{display:none}}@media(max-width:800px){body{padding:10px}.sheet{padding:20px}.summary{grid-template-columns:repeat(2,1fr)}.header{display:block}.period{margin-top:15px;text-align:{{ $isUrdu ? 'right' : 'left' }}}
    </style>
</head>
<body>
<div class="sheet">
    <button class="print" onclick="window.print()">@lang('messages.print_report')</button>
    <header class="header"><div><h1>@lang('messages.company_name')</h1><h2>@lang('messages.audit_control_report')</h2><p class="muted">@lang('messages.audit_control_period_activity')</p></div><div class="period"><strong>@lang('messages.reporting_period')</strong><br>{{ $fromDate->format('d M Y') }} - {{ $toDate->format('d M Y') }}</div></header>

    <section class="summary">
        <div class="summary-card"><div class="summary-label">@lang('messages.total_audit_events')</div><div class="summary-value">{{ number_format($audits->count()) }}</div></div>
        <div class="summary-card"><div class="summary-label">@lang('messages.users_active')</div><div class="summary-value">{{ number_format($userCounts->count()) }}</div></div>
        <div class="summary-card"><div class="summary-label">@lang('messages.models_changed')</div><div class="summary-value">{{ number_format($modelCounts->count()) }}</div></div>
        <div class="summary-card"><div class="summary-label">@lang('messages.updates')</div><div class="summary-value">{{ number_format($eventCounts->get('updated', 0)) }}</div></div>
        <div class="summary-card danger"><div class="summary-label">@lang('messages.deletions')</div><div class="summary-value">{{ number_format($eventCounts->get('deleted', 0)) }}</div></div>
    </section>

    <section class="section"><h3>@lang('messages.control_overview')</h3><table><thead><tr><th>@lang('messages.control_metric')</th><th class="number">@lang('messages.count')</th><th>@lang('messages.control_interpretation')</th></tr></thead><tbody><tr><td>@lang('messages.created_records')</td><td class="number">{{ $eventCounts->get('created', 0) }}</td><td>@lang('messages.created_records_note')</td></tr><tr><td>@lang('messages.updated_records')</td><td class="number">{{ $eventCounts->get('updated', 0) }}</td><td>@lang('messages.updated_records_note')</td></tr><tr><td>@lang('messages.deleted_records')</td><td class="number">{{ $eventCounts->get('deleted', 0) }}</td><td class="{{ $eventCounts->get('deleted', 0) ? 'badge danger' : 'badge' }}">{{ $eventCounts->get('deleted', 0) ? __('messages.review_required') : __('messages.no_deletions_detected') }}</td></tr></tbody></table></section>

    <section class="section"><h3>@lang('messages.activity_by_model')</h3><table><thead><tr><th>@lang('messages.model')</th><th class="number">@lang('messages.events')</th></tr></thead><tbody>@forelse($modelCounts as $model => $count)<tr><td>{{ class_basename($model) }}</td><td class="number">{{ $count }}</td></tr>@empty<tr><td colspan="2" class="empty">@lang('messages.no_audit_data')</td></tr>@endforelse</tbody></table></section>

    <section class="section"><h3>@lang('messages.activity_by_user')</h3><table><thead><tr><th>@lang('messages.user')</th><th class="number">@lang('messages.events')</th></tr></thead><tbody>@forelse($userCounts as $userId => $count) @php($user = $audits->firstWhere('user_id', $userId)?->user) <tr><td>{{ $user ? ($isUrdu ? ($user->name_ur ?: $user->name_en) : $user->name_en) : __('messages.system') }}</td><td class="number">{{ $count }}</td></tr>@empty<tr><td colspan="2" class="empty">@lang('messages.no_audit_data')</td></tr>@endforelse</tbody></table></section>

    <section class="section"><h3>@lang('messages.audit_event_detail')</h3><table><thead><tr><th>@lang('messages.date')</th><th>@lang('messages.user')</th><th>@lang('messages.model')</th><th>@lang('messages.event')</th><th>@lang('messages.record_id')</th><th>@lang('messages.changes')</th></tr></thead><tbody>@forelse($audits as $audit)<tr><td>{{ $audit->created_at?->format('d M Y H:i') }}</td><td>{{ $audit->user ? ($isUrdu ? ($audit->user->name_ur ?: $audit->user->name_en) : $audit->user->name_en) : __('messages.system') }}</td><td>{{ class_basename($audit->auditable_type) }}</td><td><span class="badge {{ $audit->event === 'deleted' ? 'danger' : '' }}">{{ ucfirst($audit->event) }}</span></td><td>{{ $audit->auditable_id }}</td><td><pre>{{ json_encode(['old' => $audit->old_values, 'new' => $audit->new_values], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></td></tr>@empty<tr><td colspan="6" class="empty">@lang('messages.no_audit_data')</td></tr>@endforelse</tbody></table></section>
    <div class="footer">@lang('messages.generated_on') {{ now()->format('d M Y H:i') }}</div>
</div>
</body>
</html>
